[package]
name = "esearchstat"
description = "A high-performance desktop GUI for incredibly fast text searching, powered by ripgrep."
version = "1.0.0-rc.1"
edition = "2024"
license = "MIT"
documentation = "https://docs.rs/esearchstat"
repository = "https://github.com/xangelix/esearchstat"
authors = ["Cody Wyatt Neiman (xangelix) <neiman@cody.to>"]
categories = [
    "gui",
    "filesystem",
    "visualization",
    "concurrency",
    "development-tools",
]
keywords = ["ripgrep", "grep", "code-search", "egui", "search"]

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
crossbeam-channel = "0.5.15"
eframe = { version = "0.34.3", default-features = false, features = [
    "wgpu",
    "wayland",
    "default_fonts",
] }
grep-regex = "0.1.14"
grep-searcher = { version = "0.1.16", features = ["avx-accel", "simd-accel"] }
ignore = { version = "0.4.26", features = ["simd-accel"] }
memmap2 = "0.9.10"
open = "5.3.5"
regex = { version = "1.12.4", features = ["use_std"] }
rfd = "0.17.2"
thiserror = "2.0.18"

[[bin]]
name = "esearchstat"
path = "src/bin/esearchstat.rs"
